version: '3.5'

services:
  my_app:
    container_name: my_fisrt_parser
    restart: on-failure
    build: 
      dockerfile: ./parser_project/Dockerfile
    ports:
      - 5001:5001
    command: python3 app.py